### PR TITLE
Removing possibly dead code.

### PR DESCRIPTION
**Pull request by nglx**
This removes the code which is not in fact need. The API is tested with and without ActiveSupport.

### CODE REVIEW

**Comment by pallymore** [comment]
hmmm why are you removing `SerializableCollection`

**Comment by nglx** [comment]
Well, why do we need it?
Both as_json, to_json methods are kinda convoluted and and it's working properly without them so I decided to remove the whole module.
But we can have it.

**Comment by pallymore** [comment]
I don't think the original to_json outputs all the models in the collection in json format 

also - I think it's natural to output only the collection array but not the params when doing `colleciton.to_json`

**Comment by nglx** [comment]
1. it does i believe (tested it with and without active-support)
2. agree

let me close it then.

**Pull request closed without merging**
